{
 "title": "System",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Filesystem  space available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes {instance=\"nodeexporter:9100\", job=\"nodeexporter\", mountpoint=\"/\"}",
     "legendFormat": "Filesystem  free space available"
    }
   ]
  },
  {
   "title": "Free memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "avg_over_time (node_memory_MemFree_bytes{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}[10s])\r\n\r",
     "legendFormat": "Free memory"
    }
   ]
  },
  {
   "title": "CPU utlization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU itilization"
    }
   ]
  },
  {
   "title": "CPU load average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "CPU LA1" },
    { "expr": "node_load5", "legendFormat": "CPU LA5" },
    { "expr": "node_load15", "legendFormat": "CPU LA15" }
   ]
  }
 ]
}